<a href="https://colab.research.google.com/github/KavyaPratap/Learning/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
#creating an array
a=np.array([1,5,3,4,2])
#creating 0-dimension[0D] array
zerod=np.array(42)
#1d array
oned=np.array([1,2,3,4,5])
#2d array
twod=np.array([[1,2,3],[4,5,6],[7,8,9]])
#3d array
threed=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a,type(a))
print()
print(zerod,type(zerod))
print()
print(oned,type(oned))
print()
print(twod,type(twod))
print()
print(threed,type(threed))

[1 5 3 4 2] <class 'numpy.ndarray'>

42 <class 'numpy.ndarray'>

[1 2 3 4 5] <class 'numpy.ndarray'>

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] <class 'numpy.ndarray'>


In [ ]:
#numpy array indexing

import numpy as np

a=np.array([1,2,6,4,3,2,7,8,9])
print(a)
print(a[1])
#all index of array
for i in range(len(a)):
    print(a[i],"at index-->",i)

#adding 3rdand 4th index
print(a[2]+a[3])


#for multidimensional array-->

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

[1 2 6 4 3 2 7 8 9]
2
1 at index--> 0
2 at index--> 1
6 at index--> 2
4 at index--> 3
3 at index--> 4
2 at index--> 5
7 at index--> 6
8 at index--> 7
9 at index--> 8
10
5th element on 2nd row:  10


Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) #slicing
print(arr[4:]) #end of array
print(arr[:4]) #negative slicing
print(arr[-3:-1]) #negative slicing
print(arr[1:5:2]) #step
print(arr[::2]) #every other element
print()
#slicing 2d array
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[1, 1:4]) #From the second element, slice elements from index 1 to index 4 (not included):
print(arr2[0:2, 1:4]) #From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]

[7 8 9]
[[2 3 4]
 [7 8 9]]


##Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"<br>
integer - used to represent integer numbers. e.g. -1, -2, -3<br>
float - used to represent real numbers. e.g. 1.2, 42.42<br>
boolean - used to represent True or False.<br>
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j<br>
##Data Types in NumPy<br>
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer<br>
b - boolean<br>
u - unsigned integer<br>
f - float<br>
c - complex float<br>
m - timedelta<br>
M - datetime<br>
O - object<br>
S - string<br>
U - unicode string<br>
V - fixed chunk of memory for other type ( void )<br>

In [ ]:
#getting datatype of object
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr2 = np.array(['apple', 'banana', 'cherry'])

print(arr2.dtype)


int64
<U6


In [ ]:
"""
Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:
"""
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


# For i, u, f, S and U we can define size as well.

# Example
# Create an array with data type 4 bytes integer:
# import numpy as np
# arr = np.array([1, 2, 3, 4], dtype='i4')
# print(arr)
# print(arr.dtype)

# A non integer string like 'a' can not be converted to integer (will raise an error):

# import numpy as np

# arr = np.array(['a', '2', '3'], dtype='i')

[b'1' b'2' b'3' b'4']
|S1


##Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int) #if we use 'i' thn int32 would be the dtype

print(newarr)
print(newarr.dtype)

arr2 = np.array([1, 0, 3])

newarr2 = arr2.astype(bool)
print(arr2)
print(arr2.astype('i').dtype)
print(newarr2)
print(newarr2.dtype)

[1 2 3]
int64
[1 0 3]
int32
[ True False  True]
bool


##The Difference Between Copy and View
The main difference between a copy and a view of an array is that the **copy is a new array**, and the **view is just a view of the original array**.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print("copy()---")
print(arr)
print(x)

print("view()---")
arr2 = np.array([1, 2, 3, 4, 5])
x = arr2.view()
print(x,"<--original")
x[0]=31
print(arr2)
print(x)

copy()---
[42  2  3  4  5]
[1 2 3 4 5]
view()---
[1 2 3 4 5] <--original
[31  2  3  4  5]
[31  2  3  4  5]


##Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
#shape of an array is the dimension of array like 1,1 , 2,4 etc
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [ ]:

#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


##NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
'''Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:
'''
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print('normal-->',arr)
newarr = arr.reshape(4, 3)
print()
print(newarr)
newarr2=newarr = arr.reshape(2, 2, 3)
print()
print(newarr2)
#for 3d this can be done:- newarr = arr.reshape(2, 3, 2)

normal--> [ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


##**NOTE--**
Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

##**ALSO NOTE THAT--** arr.reshape() returns the original array, so it is a view.


##Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

Example
Convert 1D array with 8 elements to 3D array with 2x2 elements:



In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


## Iterating Arrays

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in NumPy, we can do this using basic for loops of Python.

If we iterate on a 1-D array, it will go through each element one by one.

### Example

Iterate on the elements of the following 1-D array:
```python
import numpy as np

arr = np.array([1, 2, 3])
for x in arr:
    print(x)
```
## Iterating 2-D Arrays

In a 2-D array, iteration goes through all the rows.

### Example

Iterate on the elements of a 2-D array:
```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)
```

If we iterate on an n-D array, it will go through the (n−1)th dimension one by one.

To return the actual scalar values, we must iterate through every dimension.

### Example

Iterate on each scalar element of the 2-D array:
```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)
```
## Iterating 3-D Arrays

In a 3-D array, iteration goes through all the 2-D arrays.

### Example

Iterate on the elements of the following 3-D array:
```python
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)
```

To return the scalar values, iterate through each dimension:

### Example

Iterate down to the scalars:
```python
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)
```

    

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

nditer() is a helper function that supports both basic and advanced iteration.

It solves many problems we face in nested loops, especially with high-dimensional arrays.

## Iterating on Each Scalar Element

Without nditer(), iterating through each scalar of an n-D array requires n nested loops.
nditer() makes this easy.

### Example

Iterate through the following 3-D array:
```python
import numpy as np

arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)
```
## Iterating Array With Different Data Types

We can use the op_dtypes argument to cast datatype during iteration.

NumPy does not change the data type of the element in-place.
So it needs extra buffer space, enabled using:

flags=['buffered']

### Example

Iterate through the array as a string:
```python
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)
```
## Iterating With Different Step Size

We can use slicing (filtering) before iteration.

### Example

Iterate through every scalar element of the 2-D array skipping 1 element:
```python
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)
```
# Enumerated Iteration Using ndenumerate()

Enumeration means listing items along with their index.

ndenumerate() returns both:

index

value

simultaneously.

### Example

Enumerate elements of a 1-D array:
```python
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)
```

### Example

Enumerate elements of a 2-D array:
```python
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)


In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

print("\n\nIterate through every scalar element of the 2-D array skipping 1 element:\n")

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)
print("\n\nenumerate--->\n\n")

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

print("\n\nIterate through the array as a string:\n\n")

import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

1
2
3
4
5
6
7
8


Iterate through every scalar element of the 2-D array skipping 1 element:

1
3
5
7


enumerate--->


(0,) 1
(1,) 2
(2,) 3


Iterate through the array as a string:


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


##Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

print("\nFor 2-D array->\n")
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[1 2 3 4 5 6]

For 2-D array->

[[1 2 5 6]
 [3 4 7 8]]


##Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [8]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


#NumPy provides a helper function: hstack() to stack along rows.

import numpy as np
print("\nNumPy provides a helper function: hstack() to stack along rows.")
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


#Stacking Along Columns
#NumPy provides a helper function: vstack()  to stack along columns.
print("\nNumPy provides a helper function: vstack()  to stack along columns.")
#Example
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

#NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
print("\nNumPy provides a helper function: dstack() to stack along height, which is the same as depth.")
#Example

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[1 4]
 [2 5]
 [3 6]]

NumPy provides a helper function: hstack() to stack along rows.
[1 2 3 4 5 6]

NumPy provides a helper function: vstack()  to stack along columns.
[[1 2 3]
 [4 5 6]]

NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
[[[1 4]
  [2 5]
  [3 6]]]


##Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
```

##Split Into Arrays
The return value of the array_split() method is a list containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)
```
##Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

```python
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)
```

#Example
```python
Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)
```

The example above returns three 2-D arrays.

In addition, you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the column (axis=1).

#Example
```python
Split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)
```

#An alternate solution is using hsplit() opposite of hstack()


Example
```python
Use the hsplit() method to split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

```

##Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)
```

##Find the indexes where the value is 4:
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)
```
The example above will return a tuple: (array([3, 5, 6],)


Find the indexes where the values are even:
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

#similarly for add it can be done as arr%2==1
```

#Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

important-->**The searchsorted() method is assumed to be used on sorted arrays**


Example
Find the indexes where the value 7 should be inserted:

```python

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

```
Example explained: The number 7 should be inserted on index 1 to remain the sort order.

The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.


#Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.

```python
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)
```
Example explained: The number 7 should be inserted on index 2 to remain the sort order.

The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.

**To pass multiple values we give arguments like (arr,[2,4,6])** fot this the return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.





##Sorting Arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.
```python
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
```
**Note: This method returns a copy of the array, leaving the original array unchanged.**

<br>

we can also sort arrays of string or any other datatype as well...
```python
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

```
sorting of booleans-->
```python
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))
```

2-D Sort-->
```python
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))
```

In [11]:
import numpy as np
#int sorting
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

#string
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

#boolean
arr = np.array([True, False, True])
print(np.sort(arr))

#2d
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


##Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

**A boolean index list is a list of booleans corresponding to indexes in the array.**

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

**Example:** Get your own Python Server
Create an array from the elements on index 0 and 2:
```python
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)
```
The example above will return [41, 43], why?

Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

<br><br>

Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

Example
Create a filter array that will return only values higher than 42:
```python
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)
```

##Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

**Example:**Create a filter array that will return only even elements from the original array:

```python

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)
```

In [15]:
import numpy as np

#Filtering Arrays

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr,"\n\n")

#conditional filter, ex-> returning value which are greater than 42
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr,"\n\n")



#Creating Filter Directly From Array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[41 43] 


[False, False, True, True]
[43 44] 


[False  True False  True False  True False]
[2 4 6]
